program ::= declaration+
declaration ::= variable
declaration ::= function
variable ::= type declarator SEMI
declarator ::= ID
function ::= type ID LPAREN parameters? RPAREN block
parameters ::= formalParameter (COMMA formalParameter)*
formalParameter ::= type declarator
type ::= TYPE_INT 
type ::= TYPE_CHAR
block ::= LBrace variable* stat* RBrace
stat ::= forStat
stat ::= expr SEMI
stat ::= block
stat ::= assignStat SEMI
stat ::= SEMI
forStat ::= FOR LPAREN assignStat SEMI expr SEMI assignStat RPAREN block
assignStat ::= ID ASSIGN expr
expr ::=  condExpr
condExpr ::= aexpr
condExpr ::= aexpr EQ aexpr
condExpr ::= aexpr LT aexpr
aexpr ::= atom (PLUS atom)*
atom ::= ID
atom ::= INT
atom ::= LPAREN expr RPAREN 
